/**
 * Runs wrangler for one corpus: merges wrangler.jsonc (shared settings) with the corpus file
 * into wrangler.generated.jsonc and passes it to wrangler with -c.
 *
 *   npm run deploy  [-- --corpus corpora/mycorpus.jsonc]
 *   npm run dev     [-- --corpus corpora/mycorpus.jsonc]
 *   npm run wrangler -- secret put PINECONE_API_KEY [--corpus corpora/mycorpus.jsonc]
 *
 * Without --corpus, CORPUS from .env is used.
 */
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import { readCorpus, readJsonc, takeCorpusArg, WRANGLER_BASE_PATH, WRANGLER_GENERATED_PATH } from "./lib/corpus";

const args: string[] = process.argv.slice(2);
const corpus = (() => {
  try {
    return readCorpus(takeCorpusArg(args));
  } catch (err) {
    console.error(`❌ ${err instanceof Error ? err.message : err}`);
    process.exit(1);
    throw err;
  }
})();

const base = readJsonc<Record<string, unknown>>(WRANGLER_BASE_PATH);
const generated = {
  ...base,
  name: corpus.worker,
  vars: corpus.mergedVars,
  ...(corpus.r2_bucket ? { r2_buckets: [{ binding: "DOCS_BUCKET", bucket_name: corpus.r2_bucket }] } : {}),
};

fs.writeFileSync(
  WRANGLER_GENERATED_PATH,
  `// GENERATED by scripts/wrangler.ts from wrangler.jsonc + ${corpus.file.replace(/\\/g, "/").split("/").slice(-2).join("/")}. Do not edit.\n` +
    JSON.stringify(generated, null, 2) +
    "\n"
);
console.log(`▶ corpus "${corpus.corpus}" → worker "${corpus.worker}"${corpus.r2_bucket ? `, R2 "${corpus.r2_bucket}"` : ""}\n`);

const res = spawnSync("npx", ["wrangler", ...args, "-c", WRANGLER_GENERATED_PATH], { stdio: "inherit", shell: true });
process.exit(res.status ?? 1);
